### ISSUE TITLE
对 Linux 的支持

### ISSUE THREAD

**Issue by Auxxxxlx** [GreathingsDesign/Thorn-Writing#2]
荆棘写作将会支持 Linux 版，但是发布日期会稍微延后，我们会在 Beta 测试的末期对 Linux 版本进行测试。我们优先级最高的是迭代 Windows 和 macOS 版本。

我们认为在 Linux 平台进行文章创作，这是很小概率的，通常小伙伴们在 Windows 电脑或者 Mac 电脑进行写作活动。

但是，我们不会忽视来自用户的请求，如果你对 Linux 版，非常需要，请在下方评论，让我们听到你的声音，不然，我们只能将 Linux 版优先级靠后哦，谢谢支持。

**Comment by AesopL** [comment]
linux用户应该还是挺多的，支持一波

**Comment by boltomli** [comment]
中立，希望作者能先把功能做好（目前有一些反应迟钝之类的问题，导致实际使用不便）。目前的 beta 版 Linux 下直接能跑起来，毫无压力，开发框架不变的话应该无需做很多修改和适配。
